env:
  commonjs: true
  es6: true
  node: true
  mocha: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
plugins:
  - import
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-unused-vars:
    - error
    - always
    - argsIgnorePattern: next
  eol-last:
    - error
    - always
  import/extension:
    - off
    - always
  import/no-unresolved: 0
  no-console: 0
